export const carsDetails = [
  {
    current_page: 1,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 1,
        make: "Toyota",
        model: "Camry",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.5,
        price_per_day: 50.0,
        available: true,
        image_link: require("./assets/Toyota_camry.jpg"),
      },
      {
        id: 2,
        make: "Honda",
        model: "Civic",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 16.2,
        price_per_day: 45.0,
        available: true,
        image_link: require("./assets/Honda_Civic .jpeg"),
      },
      {
        id: 3,
        make: "Ford",
        model: "Escape",
        year: 2020,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.8,
        price_per_day: 60.0,
        available: true,
        image_link: require("./assets/Ford_Escape.jpeg"),
      },
      {
        id: 4,
        make: "Jeep",
        model: "Wrangler",
        year: 2022,
        seats: 4,
        fuel_type: "Gasoline",
        transmission_type: "Manual",
        mileage_per_liter: 10.5,
        price_per_day: 65.0,
        available: true,
        image_link: require("./assets/JeepWrang.jpeg"),
      },
      {
        id: 5,
        make: "Nissan",
        model: "Altima",
        year: 2023,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 17.3,
        price_per_day: 48.0,
        available: true,
        image_link: require("./assets/NisanAltima.jpeg"),
      },
      {
        id: 6,
        make: "Chevrolet",
        model: "Tahoe",
        year: 2021,
        seats: 7,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.7,
        price_per_day: 70.0,
        available: true,
        image_link: require("./assets/Chevrolet.jpeg"),
      },
    ],
  },
  {
    current_page: 2,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 7,
        make: "Toyota",
        model: "Corolla",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.2,
        price_per_day: 42.0,
        available: true,
        image_link: require("./assets/Toyota_corolla.jpeg"),
      },
      {
        id: 8,
        make: "Ford",
        model: "F-150",
        year: 2023,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 10.8,
        price_per_day: 75.0,
        available: true,
        image_link: require("./assets/Ford_F-150.jpeg"),
      },
      {
        id: 9,
        make: "Chevrolet",
        model: "Camaro",
        year: 2022,
        seats: 4,
        fuel_type: "Gasoline",
        transmission_type: "Manual",
        mileage_per_liter: 12.0,
        price_per_day: 68.0,
        available: true,
        image_link: require("./assets/Chevrolet_camaro.jpeg"),
      },
      {
        id: 10,
        make: "BMW",
        model: "X5",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 11.9,
        price_per_day: 80.0,
        available: true,
        image_link: require("./assets/BMW_X5.jpeg"),
      },
      {
        id: 11,
        make: "Tesla",
        model: "Model Y",
        year: 2023,
        seats: 5,
        fuel_type: "Electricity",
        transmission_type: "Automatic",
        mileage_per_liter: 0.0,
        price_per_day: 90.0,
        available: true,
        image_link: require("./assets/Tesla_modle_y.jpeg"),
      },
      {
        id: 12,
        make: "Mercedes-Benz",
        model: "C-Class",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.4,
        price_per_day: 72.0,
        available: true,
        image_link: require("./assets/Mercedes-Benz_class_c.jpeg"),
      },
    ],
  },
  {
    current_page: 3,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 13,
        make: "Hyundai",
        model: "Elantra",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.3,
        price_per_day: 47.0,
        available: true,
        image_link: require("./assets/Elantra.jpeg"),
      },
      {
        id: 14,
        make: "Kia",
        model: "Sportage",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.7,
        price_per_day: 49.0,
        available: true,
        image_link: require("./assets/sportage.jpeg"),
      },
      {
        id: 15,
        make: "Volkswagen",
        model: "Passat",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 16.1,
        price_per_day: 52.0,
        available: true,
        image_link: require("./assets/passsat.jpeg"),
      },
      {
        id: 16,
        make: "Subaru",
        model: "Outback",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.9,
        price_per_day: 55.0,
        available: true,
        image_link: require("./assets/outback.jpeg"),
      },
      {
        id: 17,
        make: "Audi",
        model: "A4",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.5,
        price_per_day: 62.0,
        available: true,
        image_link: require("./assets/AudiA4.jpeg"),
      },
      {
        id: 18,
        make: "Lexus",
        model: "RX",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.8,
        price_per_day: 70.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
    ],
  },
  {
    current_page: 4,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 19,
        make: "Mazda",
        model: "CX-5",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.6,
        price_per_day: 55.0,
        available: true,
        image_link: require("./assets/AudiA4.jpeg"),
      },
      {
        id: 20,
        make: "Volvo",
        model: "XC90",
        year: 2021,
        seats: 7,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.0,
        price_per_day: 68.0,
        available: true,
        image_link: require("./assets/Mercedes-Benz_class_c.jpeg"),
      },
      {
        id: 21,
        make: "Jeep",
        model: "Grand Cherokee",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.9,
        price_per_day: 63.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
      {
        id: 22,
        make: "Hyundai",
        model: "Santa Fe",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.7,
        price_per_day: 51.0,
        available: true,
        image_link: require("./assets/sportage.jpeg"),
      },
      {
        id: 23,
        make: "Subaru",
        model: "Forester",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.5,
        price_per_day: 54.0,
        available: true,
        image_link: require("./assets/Elantra.jpeg"),
      },
      {
        id: 24,
        make: "Tesla",
        model: "Model S",
        year: 2022,
        seats: 5,
        fuel_type: "Electricity",
        transmission_type: "Automatic",
        mileage_per_liter: 0.0,
        price_per_day: 85.0,
        available: true,
        image_link: require("./assets/outback.jpeg"),
      },
    ],
  },
  {
    current_page: 5,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 25,
        make: "Audi",
        model: "Q5",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.2,
        price_per_day: 60.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
      {
        id: 26,
        make: "Lexus",
        model: "ES",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.9,
        price_per_day: 65.0,
        available: true,
        image_link: require("./assets/sportage.jpeg"),
      },
      {
        id: 27,
        make: "Mazda",
        model: "Mazda3",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 16.3,
        price_per_day: 49.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
      {
        id: 28,
        make: "Kia",
        model: "Soul",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.8,
        price_per_day: 46.0,
        available: true,
        image_link: require("./assets/Mercedes-Benz_class_c.jpeg"),
      },
      {
        id: 29,
        make: "Hyundai",
        model: "Tucson",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.5,
        price_per_day: 52.0,
        available: true,
        image_link: require("./assets/Honda_Civic .jpeg"),
      },
      {
        id: 30,
        make: "Jeep",
        model: "Compass",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.0,
        price_per_day: 50.0,
        available: true,
        image_link: require("./assets/Toyota_camry.jpg"),
      },
    ],
  },
  {
    current_page: 6,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 31,
        make: "Toyota",
        model: "Camry",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.5,
        price_per_day: 50.0,
        available: true,
        image_link: require("./assets/Toyota_camry.jpg"),
      },
      {
        id: 32,
        make: "Honda",
        model: "Civic",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 16.2,
        price_per_day: 45.0,
        available: true,
        image_link: require("./assets/Honda_Civic .jpeg"),
      },
      {
        id: 33,
        make: "Ford",
        model: "Escape",
        year: 2020,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.8,
        price_per_day: 60.0,
        available: true,
        image_link: require("./assets/Ford_Escape.jpeg"),
      },
      {
        id: 34,
        make: "Jeep",
        model: "Wrangler",
        year: 2022,
        seats: 4,
        fuel_type: "Gasoline",
        transmission_type: "Manual",
        mileage_per_liter: 10.5,
        price_per_day: 65.0,
        available: true,
        image_link: require("./assets/JeepWrang.jpeg"),
      },
      {
        id: 35,
        make: "Nissan",
        model: "Altima",
        year: 2023,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 17.3,
        price_per_day: 48.0,
        available: true,
        image_link: require("./assets/NisanAltima.jpeg"),
      },
      {
        id: 36,
        make: "Chevrolet",
        model: "Tahoe",
        year: 2021,
        seats: 7,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.7,
        price_per_day: 70.0,
        available: true,
        image_link: require("./assets/Chevrolet.jpeg"),
      },
    ],
  },
  {
    current_page: 7,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 37,
        make: "Toyota",
        model: "Corolla",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.2,
        price_per_day: 42.0,
        available: true,
        image_link: require("./assets/Toyota_corolla.jpeg"),
      },
      {
        id: 38,
        make: "Ford",
        model: "F-150",
        year: 2023,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 10.8,
        price_per_day: 75.0,
        available: true,
        image_link: require("./assets/Ford_F-150.jpeg"),
      },
      {
        id: 39,
        make: "Chevrolet",
        model: "Camaro",
        year: 2022,
        seats: 4,
        fuel_type: "Gasoline",
        transmission_type: "Manual",
        mileage_per_liter: 12.0,
        price_per_day: 68.0,
        available: true,
        image_link: require("./assets/Chevrolet_camaro.jpeg"),
      },
      {
        id: 40,
        make: "BMW",
        model: "X5",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 11.9,
        price_per_day: 80.0,
        available: true,
        image_link: require("./assets/BMW_X5.jpeg"),
      },
      {
        id: 41,
        make: "Tesla",
        model: "Model Y",
        year: 2023,
        seats: 5,
        fuel_type: "Electricity",
        transmission_type: "Automatic",
        mileage_per_liter: 0.0,
        price_per_day: 90.0,
        available: true,
        image_link: require("./assets/Tesla_modle_y.jpeg"),
      },
      {
        id: 42,
        make: "Mercedes-Benz",
        model: "C-Class",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.4,
        price_per_day: 72.0,
        available: true,
        image_link: require("./assets/Mercedes-Benz_class_c.jpeg"),
      },
    ],
  },
  {
    current_page: 8,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 43,
        make: "Hyundai",
        model: "Elantra",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.3,
        price_per_day: 47.0,
        available: true,
        image_link: require("./assets/Elantra.jpeg"),
      },
      {
        id: 44,
        make: "Kia",
        model: "Sportage",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.7,
        price_per_day: 49.0,
        available: true,
        image_link: require("./assets/sportage.jpeg"),
      },
      {
        id: 45,
        make: "Volkswagen",
        model: "Passat",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 16.1,
        price_per_day: 52.0,
        available: true,
        image_link: require("./assets/passsat.jpeg"),
      },
      {
        id: 46,
        make: "Subaru",
        model: "Outback",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.9,
        price_per_day: 55.0,
        available: true,
        image_link: require("./assets/outback.jpeg"),
      },
      {
        id: 47,
        make: "Audi",
        model: "A4",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.5,
        price_per_day: 62.0,
        available: true,
        image_link: require("./assets/AudiA4.jpeg"),
      },
      {
        id: 48,
        make: "Lexus",
        model: "RX",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.8,
        price_per_day: 70.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
    ],
  },
  {
    current_page: 9,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 49,
        make: "Mazda",
        model: "CX-5",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.6,
        price_per_day: 55.0,
        available: true,
        image_link: require("./assets/AudiA4.jpeg"),
      },
      {
        id: 50,
        make: "Volvo",
        model: "XC90",
        year: 2021,
        seats: 7,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.0,
        price_per_day: 68.0,
        available: true,
        image_link: require("./assets/Mercedes-Benz_class_c.jpeg"),
      },
      {
        id: 51,
        make: "Jeep",
        model: "Grand Cherokee",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.9,
        price_per_day: 63.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
      {
        id: 52,
        make: "Hyundai",
        model: "Santa Fe",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.7,
        price_per_day: 51.0,
        available: true,
        image_link: require("./assets/sportage.jpeg"),
      },
      {
        id: 53,
        make: "Subaru",
        model: "Forester",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 13.5,
        price_per_day: 54.0,
        available: true,
        image_link: require("./assets/Elantra.jpeg"),
      },
      {
        id: 54,
        make: "Tesla",
        model: "Model S",
        year: 2022,
        seats: 5,
        fuel_type: "Electricity",
        transmission_type: "Automatic",
        mileage_per_liter: 0.0,
        price_per_day: 85.0,
        available: true,
        image_link: require("./assets/outback.jpeg"),
      },
    ],
  },
  {
    current_page: 10,
    cars_per_page: 6,
    total_pages: 10,
    cars: [
      {
        id: 55,
        make: "Audi",
        model: "Q5",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.2,
        price_per_day: 60.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
      {
        id: 56,
        make: "Lexus",
        model: "ES",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 12.9,
        price_per_day: 65.0,
        available: true,
        image_link: require("./assets/sportage.jpeg"),
      },
      {
        id: 57,
        make: "Mazda",
        model: "Mazda3",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 16.3,
        price_per_day: 49.0,
        available: true,
        image_link: require("./assets/RX.jpeg"),
      },
      {
        id: 58,
        make: "Kia",
        model: "Soul",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 15.8,
        price_per_day: 46.0,
        available: true,
        image_link: require("./assets/Mercedes-Benz_class_c.jpeg"),
      },
      {
        id: 59,
        make: "Hyundai",
        model: "Tucson",
        year: 2022,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.5,
        price_per_day: 52.0,
        available: true,
        image_link: require("./assets/Honda_Civic .jpeg"),
      },
      {
        id: 60,
        make: "Jeep",
        model: "Compass",
        year: 2021,
        seats: 5,
        fuel_type: "Gasoline",
        transmission_type: "Automatic",
        mileage_per_liter: 14.0,
        price_per_day: 50.0,
        available: true,
        image_link: require("./assets/Toyota_camry.jpg"),
      },
    ],
  },
];
